<?php
session_start();
# RETRIEVE THE CHAIN STORED IN THE SESSION, EUNSUREING THAT THE URL MATCHES, ALLOWS FOR USING THE RESULTS OF A ROUTE ON A PAGE, SUCH AS SUCCESS, FORMS, INVOICES ETC

//!! ADD URL CHECK LATER

print_r('SESSION: ');
print_r($_SESSION['VIEW_ROUTE']);
$ARR_ViewRoute = $_SESSION['VIEW_ROUTE'];

//!! PREVENT XSS ATTACKS HERE
$ARR_Chain = $ARR_ViewRoute['ARR_Chain'];

?>
